spring:
  profiles:
    include: oauth, jwt
  security:
    user:
      password: 1
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio?currentSchema=english_study_web
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update